
### get trips
GET https://api.mariscosduenas.com/api/clientes
content-type: application/json

### get clientes payment account
GET https://api.mariscosduenas.com/api/ventas/pendientes/671d9db61beeb2310e4a89d2

### get trips
GET https://api.mariscosduenas.com/api/productos
content-type: application/json

### get trips
GET https://api.mariscosduenas.com/api/productos/672d8ddb283c69888fc6b2b4
content-type: application/json

### get trips
GET https://api.mariscosduenas.com/api/salidas
content-type: application/json

### get trips
GET https://api.mariscosduenas.com/api/salidas
content-type: application/json

### get ventas por rango de fecha
GET https://api.mariscosduenas.com/api/ventasReport/rango-fechas?fechaInicio=2024-12-01&fechaFin=2024-12-22
content-type: application/json

### get ventas por rango de fecha
GET http://127.0.0.1:3000/api/ventasReport/rango-fechas?fechaInicio=2024-12-01&fechaFin=2024-12-05
content-type: application/json



### get trips
GET https://api.mariscosduenas.com/api/ventas
content-type: application/json


### register user
POST https://api.mariscosduenas.com/api/register
content-type: application/json

{
    "username": "alejandro",
    "password": "alelor$$"
}

### login
POST https://api.mariscosduenas.com/api/login
content-type: application/json

{
    "username": "alejandro",
    "password": "alelor$$"
}

### post trip
POST https://api.mariscosduenas.com/api/clientes
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "nombre": "Farallones",
    "direccion": "Carretera litoral local 13, el majahual, La libertad",
    "telefono": "74323123"
}

### post proveedor
POST https://api.mariscosduenas.com/api/proveedores
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "nombre": "Juana and Co.",
    "direccion": "Jiquilisco, Usulutan",
    "telefono": "79148719",
    "email": "proveedor.sv@gmail.com"
}

### post proveedor
POST https://api.mariscosduenas.com/api/productos
content-type: application/json
//auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "nombre": "Concha Grande",
    
}

### post salida
POST https://api.mariscosduenas.com/api/salidas
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "product_id": "664ccdfdd08a0f8d6377ba0f",
    "cantidad": 50,
    "motivo": "El producto se arruino"
}


### post venta
POST http://127.0.0.1:3000/api/ventas
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "productos": [
        {
            "producto_id": "671d9db61beeb2310e4a89d2",
            "entrada_id": "673966cb494fe664c3c546c6",
            "cantidad": 50,
            "precio_venta": 3.6
        },
        {
            "producto_id": "672d8ddb283c69888fc6b2b4",
            "entrada_id": "673966e3494fe664c3c54703",
            "cantidad": 50,
            "precio_venta": 20
        }
    ],
    "pagos": [],
    "estado": "PENDIENTE",
    "cliente_id": "672d462dfecdf31c02599ce1"
}

### post ventas multiple
POST https://api.mariscosduenas.com/api/ventas/multiple
content-type: application/json

{
    "ventas": [
        {
            "productos": [
                {
                    "producto_id": "671d9db61beeb2310e4a89d2",
                    "entrada_id": "664ccdfdd08a0f8d6377ba0f",
                    "cantidad": 50,
                    "precio_venta": 0.75
                }
            ],
            "pagos": [],
            "cliente_id": "664b7ce21322fdbb387eddf8"
        },
        {
            "productos": [
                {
                    "producto_id": "671d9db61beeb2310e4a89d2",
                    "entrada_id": "664ccdfdd08a0f8d6377ba10",
                    "cantidad": 30,
                    "precio_venta": 1.00
                }
            ],
            "pagos": [],
            "cliente_id": "664b7ce21322fdbb387eddf8"
        }
    ]
}


### post entrada
POST https://api.mariscosduenas.com/api/ventas/664cce3bd08a0f8d6377ba19/pagos
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "fecha": "2024-05-21",
    "monto": 25
}

### post entrada
PUT  https://api.mariscosduenas.com/api/ventas/664cce3bd08a0f8d6377ba19/estado
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiN2I0NTEzMjJmZGJiMzg3ZWRkZjMiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTYyMjMwNjUsImV4cCI6MTcxNjI1MTg2NX0.4M6lqpaIVlYlYiFAl_c_6oznumGDdy9g4Hx897YfZa8

{
    "estado_pago": "parcial"
}
